name: Sample espresso tests on browser stack
on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  android-sdk-sandbox-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Chceckout Repo
        uses: actions/checkout@v2

      - name: Run tests on browser stack
        run: |
          curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" -d '{"app": ${{ secrets.APP_URL }}, "testSuite": ${{ secrets.TEST_APP_URL }}, "devices": ["Samsung Galaxy S23 Ultra-13.0"]}' -H "Content-Type: application/json"
