name: Sample espresso tests on browser stack
on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  android-sdk-sandbox-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Chceckout Repo
        uses: actions/checkout@v2

      - name: Run tests on browser stack
        run: |
          curl -u "vivekjain_Vv8MWH:zUnKgGaexuxr3m3zGF2j" -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" -d '{"app": "bs://0ee11d256e1e8be0eaeac1f1d8937cd5230bf257", "testSuite": "bs://45fd392929a6ec3d0fa871581fc9f64ad587d576", "devices": ["Samsung Galaxy S23 Ultra-13.0"]}' -H "Content-Type: application/json"

      # - name: Run tests on browser stack
      #   run: |
      #     curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" \
      #     -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
      #     -d '{"devices": ["Samsung Galaxy S23 Ultra-13.0"], "app": ${{ secrets.APP_URL }} , "testSuite": ${{ secrets.TEST_APP_URL }}}' \
      #     -H "Content-Type: application/json"